### ISSUE TITLE
Borrowing icons from devicon

### ISSUE THREAD

**Issue by amilajack** [henrikdahl/hyper-tabs-enhanced#3]
[devicon.fr](http://devicon.fr) as a lot of icons that this repo can take advantage of. What are your thoughts on adding some kind of integration for them? I am willing to make a PR for this

**Comment by henrikruscon** [comment]
Do you prefer them over the existing icons or is the idea to expand upon the few that already exist?

So far I've been designing my own based on existing ones since for example I personally think the gulp text on gulp icon looks like gibberish at smaller sizes. Vim one looks overly complicated, PHP one has too many details to translate on smaller sizes, etc.

I'm not set in my way though, I'm open to changing ✌️

**Comment by amilajack** [comment]
Good idea. We can definitely modify them by cutting down on smaller shapes.

**Comment by henrikruscon** [comment]
If there's a particular process icon you're lacking right now let me know and I'll add it in to start with.
